# Generated by Django 5.2.7 on 2025-10-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_is_completed_todoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
